// Code generated by db/gen/gen.go; DO NOT EDIT.
package db

func (model UserModel) IDTag() string {
	return "_id"
}

func (model UserModel) UserIDTag() string {
	return "user_id"
}

func (model UserModel) DeletedAtTag() string {
	return "deleted_at"
}

func (model UserModel) UpdatedAtTag() string {
	return "updated_at"
}

func (model UserModel) CreatedAtTag() string {
	return "created_at"
}
