// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.2
// source: op-service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Request data to create new op
type NewUserRegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewUserRegistrationRequest) Reset() {
	*x = NewUserRegistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRegistrationRequest) ProtoMessage() {}

func (x *NewUserRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRegistrationRequest.ProtoReflect.Descriptor instead.
func (*NewUserRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_op_service_proto_rawDescGZIP(), []int{0}
}

// Contains data of created op
type NewUserRegistrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewUserRegistrationResponse) Reset() {
	*x = NewUserRegistrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRegistrationResponse) ProtoMessage() {}

func (x *NewUserRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_op_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRegistrationResponse.ProtoReflect.Descriptor instead.
func (*NewUserRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_op_service_proto_rawDescGZIP(), []int{1}
}

var File_op_service_proto protoreflect.FileDescriptor

var file_op_service_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x70, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x1d, 0x0a, 0x1b, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x8b, 0x01, 0x0a, 0x09, 0x4f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a,
	0x13, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x22, 0x1b, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x42, 0xbf, 0x01,
	0x5a, 0x04, 0x2e, 0x3b, 0x76, 0x31, 0x92, 0x41, 0xb5, 0x01, 0x12, 0x4f, 0x0a, 0x0a, 0x4f, 0x70,
	0x20, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x3c, 0x0a, 0x02, 0x6f, 0x70, 0x12, 0x22,
	0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x61, 0x61, 0x62, 0x68, 0x69, 0x6c, 0x61, 0x73, 0x68, 0x39, 0x37, 0x2f,
	0x6f, 0x70, 0x1a, 0x12, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x40, 0x61, 0x6d, 0x73, 0x6f, 0x6b,
	0x6f, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x32, 0x03, 0x31, 0x2e, 0x30, 0x2a, 0x01, 0x01, 0x32, 0x10,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e,
	0x3a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73,
	0x6f, 0x6e, 0x52, 0x3b, 0x0a, 0x03, 0x34, 0x30, 0x34, 0x12, 0x34, 0x0a, 0x2a, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x65, 0x64, 0x20, 0x77, 0x68, 0x65, 0x6e, 0x20, 0x74, 0x68, 0x65, 0x20, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x20, 0x64, 0x6f, 0x65, 0x73, 0x20, 0x6e, 0x6f, 0x74,
	0x20, 0x65, 0x78, 0x69, 0x73, 0x74, 0x2e, 0x12, 0x06, 0x0a, 0x04, 0x9a, 0x02, 0x01, 0x07, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_op_service_proto_rawDescOnce sync.Once
	file_op_service_proto_rawDescData = file_op_service_proto_rawDesc
)

func file_op_service_proto_rawDescGZIP() []byte {
	file_op_service_proto_rawDescOnce.Do(func() {
		file_op_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_op_service_proto_rawDescData)
	})
	return file_op_service_proto_rawDescData
}

var file_op_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_op_service_proto_goTypes = []interface{}{
	(*NewUserRegistrationRequest)(nil),  // 0: v1.NewUserRegistrationRequest
	(*NewUserRegistrationResponse)(nil), // 1: v1.NewUserRegistrationResponse
}
var file_op_service_proto_depIdxs = []int32{
	0, // 0: v1.OpService.NewUserRegistration:input_type -> v1.NewUserRegistrationRequest
	1, // 1: v1.OpService.NewUserRegistration:output_type -> v1.NewUserRegistrationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_op_service_proto_init() }
func file_op_service_proto_init() {
	if File_op_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_op_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewUserRegistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewUserRegistrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_op_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_op_service_proto_goTypes,
		DependencyIndexes: file_op_service_proto_depIdxs,
		MessageInfos:      file_op_service_proto_msgTypes,
	}.Build()
	File_op_service_proto = out.File
	file_op_service_proto_rawDesc = nil
	file_op_service_proto_goTypes = nil
	file_op_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OpServiceClient is the client API for OpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpServiceClient interface {
	// RegistrationUser new op task
	NewUserRegistration(ctx context.Context, in *NewUserRegistrationRequest, opts ...grpc.CallOption) (*NewUserRegistrationResponse, error)
}

type opServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpServiceClient(cc grpc.ClientConnInterface) OpServiceClient {
	return &opServiceClient{cc}
}

func (c *opServiceClient) NewUserRegistration(ctx context.Context, in *NewUserRegistrationRequest, opts ...grpc.CallOption) (*NewUserRegistrationResponse, error) {
	out := new(NewUserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/v1.OpService/NewUserRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpServiceServer is the server API for OpService service.
type OpServiceServer interface {
	// RegistrationUser new op task
	NewUserRegistration(context.Context, *NewUserRegistrationRequest) (*NewUserRegistrationResponse, error)
}

// UnimplementedOpServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOpServiceServer struct {
}

func (*UnimplementedOpServiceServer) NewUserRegistration(context.Context, *NewUserRegistrationRequest) (*NewUserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUserRegistration not implemented")
}

func RegisterOpServiceServer(s *grpc.Server, srv OpServiceServer) {
	s.RegisterService(&_OpService_serviceDesc, srv)
}

func _OpService_NewUserRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpServiceServer).NewUserRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OpService/NewUserRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpServiceServer).NewUserRegistration(ctx, req.(*NewUserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OpService",
	HandlerType: (*OpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUserRegistration",
			Handler:    _OpService_NewUserRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "op-service.proto",
}
